#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'bundler/setup'
require 'warp'

Client = Warp::Client.new
Session = Warp::Session.new "email@email.com", "password"

Client.sessions << Session
Client.connect
